### ISSUE TITLE
SSL Auth with certs not working

### ISSUE THREAD

**Issue by fgather** [cliffano/nestor#34]
Hi,

do you plan to release the current git version in near time? I desperately wait for the SSL feature which is described in the readme but isn't on npm yet. 

Many Regards,
Florian

**Comment by cliffano** [comment]
Hi @fgather ,

I'm sorry it took a while.
I just published v0.3.3 which includes the SSL support contribution from Benedikt and also a minor fix on handling job object without colour status, do you mind checking v0.3.3 out?

Thanks in advance.

**Comment by cliffano** [comment]
Closing this since there's no issue raised.
