### ISSUE TITLE
NO_PROXY environment variable is not used for ignoring proxy settings

### ISSUE THREAD

**Issue by prinztob** [cliffano/nestor#36]
Hi,
Currently only localhost and 127.0.0.1 are used for ignoring proxy settings. Is there any plans to use the NO_PROXY environment variable for this in the future?

Many Regards,
Tobias

**Comment by cliffano** [comment]
I've included NO_PROXY/no_proxy support in nestor v0.3.5 .
Could you please give it a try and see if it solves your problem?

**Comment by cliffano** [comment]
@prinztob Would you be able to give nestor v0.3.5 a quick try?

**Comment by prinztob** [comment]
Thanks a lot, I just tested it and your NO_PROXY/no_proxy support solves my problem.

**Comment by cliffano** [comment]
@prinztob Thanks for your help with testing. Closing this issue now that it's solved.
