### ISSUE TITLE
interactive authentication should not result in incorrect name and/or password in Jenkins URL

### ISSUE THREAD

**Issue by paolo-tanium** [cliffano/nestor#41]
Since nestor auth works through several options (URL, token, interactive, certificate), it should not result in `  Authentication failed - incorrect username and/or password in Jenkins URL` when the user chooses an auth that is not URL. This is confusing to users who chose other authentication schemes.

**Comment by paolo-tanium** [comment]
![image](https://cloud.githubusercontent.com/assets/21039701/18697639/24cc3310-7f91-11e6-8644-e7a62737b107.png)

**Comment by cliffano** [comment]
@paolo-tanium Thanks for reporting this. I've pushed the change to update auth error messages so they no longer assume that the credential is passed through URL.

I will release a new version of Nestor tonight.

**Comment by cliffano** [comment]
Included in v1.0.0 .
