### ISSUE TITLE
Cannot ava watch and nestor at the same time

### ISSUE THREAD

**Issue by thisgeek** [cliffano/nestor#49]
I discovered today that the keeping around the `JENKINS_URL` environment variable will convince [ava][] that you are [running your tests on a continuous integration server][ava in docker]. If you run `ava --watch` with the variable set, you're [met with an error][watch mode error].

Ava's environment detection appears to be based on the [ci-info][] package. I'm not sure yet if I would say the fault lies with ci-info, nestor, or my environment setup.

[ava]: https://www.npmjs.com/package/ava
[ava in docker]: https://github.com/avajs/ava/blob/master/docs/common-pitfalls.md#ava-in-docker
[watch mode error]: https://github.com/avajs/ava/blob/master/docs/recipes/watch-mode.md#watch-mode-and-ci
[ci-info]: https://www.npmjs.com/package/ci-info

**Comment by cliffano** [comment]
@thisgeek My apology for the very late reply.
Did the fix in https://github.com/watson/ci-info/issues/4 solve the conflict for you?

**Comment by thisgeek** [comment]
@cliffano It's been a while since I checked. I believe the answer is yes.

**Comment by cliffano** [comment]
Thanks. In that case, I'll close this ticket.
Thanks for using nestor.
