### ISSUE TITLE
Nestor does not work properly with fish shell

### ISSUE THREAD

**Issue by thatside-zaraffa** [cliffano/nestor#53]
If launched inside Fish shell: 
`connect ECONNREFUSED 127.0.0.1:8080`.
Fish env variable is configured properly (`set -U JENKINS_URL ...`).
Seems Nestor uses some non-standard way to receive env variables from shell.
If launched inside Bash shell with properly exported JENKINS_URL variable - it works well.
Export launched via `bass` (Fish shell plugin allowing to execute Bash code) allows to use nestor until terminal window is open.

**Comment by cliffano** [comment]
@thatside-zaraffa nestor uses `process.env` which should be standard enough.
Could you please try this on fish shell?
`env JENKINS_URL="http://yourjenkins" nestor dashboard`

**Comment by thatside** [comment]
@cliffano sorry, I don't know where was the problem but it works pretty OK now...
